version: '3'

services:
  db:
    image: postgres:12
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    build: .
    command: gunicorn mysite.wsgi
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db-data:
